### ISSUE TITLE
inconsistencies and/or typos in instructions (recipient code)

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#140]
Text changes needed on the following pages: 

1- qsp_dg_recip_id/Choose_ID_O/2/.: 
 "All the participants in this study are given these three options:"
" Please select one of these options to form the alpha-numeric part of your personal ID."

2- qsp_dg_recip_id/Choose_Icon/3/ : 
"You **do not** need to remember which icon you have selected. Your ID will always be shown to you whenever it is necessary."

3- qsp_dg_recip_id/Results/4/ :
"You **do not** need to remember your ID. Your ID will always be shown to you whenever it is necessary."

4- dg_recip/Introduction/5/
Title should have (Part 1) on this page.
 
5-dg_recip_survey_p2/Self_Explain/24/
"Next, we would like to ask you a few questions about your own ID selection. Here is the ID you have constructed in Task 1."

6-survey_qsp/S_History/28/. (it says different gender as)
"Have you ever had any kind of sexual relations with persons of different gender(s) than yourself?"
"Have you ever been sexually attracted to or had sexual fantasies about persons of different gender(s) than yourself?"

7- survey_qsp/Prolific_Guess/33/  currently it says "and", should be "than". 
"...you think is more, less, or equally liberal than conservative on social issues? "

**Comment by ianchadd** [comment]
1 - Change ID label to "All the participants in this study are given these three options. Please select one of these options to form the alpha-numeric part of your personal ID."
2 - use icon not alpha-numeric
3 - use ID not alpha-numeric
4 - should **not** have Part 1

**Comment by boonhankoh** [comment]
DG_instructions/6: Change wording to:

**Comment by boonhankoh** [comment]
Belief elicitation screen - first time it appears with the link:

Change wording to: "Clicking the button below will provide a detailed description of how you will be paid for your predictions. You do not need to know it in detail, except that the procedure is designed so that it is in your best interest to state your guesses as accurately as possible."

Replace link with button and embedded PDF at bottom of the screen.

**Comment by boonhankoh** [comment]
dg_recip_survey/Average Guess/14:

Average amount sent to ___ : XXX ECU

Delete the "Final Guess" section.

**Comment by ianchadd** [comment]
on LGBT_Attitudes
"To what extent do you agree with the following statements"
[statements and responses]

**Comment by boonhankoh** [comment]
qsp_dg_recip_intro/introduction/1: paragraph on payment not correct.

How much payment will I receive for my participation?
You will be paid 1 USD for completing the study.

**Additionally, you may receive additional bonus payments based on your decisions in Tasks 1 or 2. At the end of the study, we will randomly pick either Task 1 or Task 2 to determine your bonus payment. Since nobody knows which task will be selected for payment, you should pay close attention to the tasks as your decisions may determine your earnings.**

SHOULD INSTEAD BE:
**Additionally, you may receive additional bonus payments based on your decisions in the tasks. Hence, you should pay close attention the tasks as your decisions may determine your earnings.**

**Comment by boonhankoh** [comment]
qsp_dg_recip_id/Choose_ID_O/2/:
Next button need to be right-aligned.

**Comment by boonhankoh** [comment]
qsp_dg_recip_id/Choose_Icon/3/:
Next button need to be right-aligned.

**Comment by boonhankoh** [comment]
4- dg_recip/Introduction/5/
Title should **not** have (Part 1) on this page.
