### ISSUE TITLE
Dictator Game: presentation of 9 ID options

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#147]
on page qsp_dg_dict_instructions/Options_List/5/

Can we make the flags a little smaller so that they look like they have the same font size as the alphanumeric part? 

We also want these IDs to look like ID handles. So slightly smaller font size may look nicer.

Lastly, if possible, can we put more vertical spacing between them. It is a little hard to see them separately in this presentation. 

@boonhankoh @ianchadd  thoughts?

**Comment by boonhankoh** [comment]
Another issue raised here: https://github.com/ianchadd/rpi_3208/issues/172

Any chance we can keep the ordering of flags the same as the previous screen?

**Comment by boonhankoh** [comment]
Agreed with @billuraksoy 's comment.

Can we instead present the 9 IDs the way they will be presented to subjects in later decision screens? So, [Flag][string] format for each ID where the flag and the string are on the same line.

It may help to put them in a 3-by-3 table with inside borders so that the 9 IDs are clearly separate from each other.

**Comment by ianchadd** [comment]
Kept the same font size (35px) and adjusted flags to be same height as alpha-numeric strings (35px), auto-width. Changed to center align in each cell, but did not add borders (too busy). I think the result looks fine for informational purposes. 

Did not change flag order since flag order is randomized in the page prior and changing this so it matches is non-trivial. If we think it is very important that the order is the same, I can revisit this later.
