### ISSUE TITLE
IRB amendment for QCP? 

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#219]
We made some significant changes to the survey questions. I think we should submit an amendment and get those approved. Lets discuss this.

**Comment by ianchadd** [comment]
i think we're actually ok on this. The approved protocol says "Sample Survey Questions" and it doesn't actually look like a definitive list of survey questions was included in the review process. So I don't think it's necessary to submit an amendment since the protocol was never meant to be exhaustive on that end.

**Comment by ianchadd** [comment]
Talked earlier this week. Decided not to do this right now.
