### ISSUE TITLE
Is there a way to define a Player method so that it works across all apps?

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/rpi_3208#231]
Example: in dg_recip_survey, I define participant_vars_dump for the player object in models.py. Then this is called in a number of pages in this app. However, the exact same method is used in several other apps, but so far I've had to copy this code into models.py for each app. This is clearly inefficient. 

Is there a way to define a method **once** somewhere in the server code so that it is automatically pushed to all Player objects, across all apps?

**Comment by mcdaij** [comment]
Yes, if you put the function in custom_templates/custom_funcs.py you can access it from anywhere and if you have it set up as a something(self): function based on the player class it will still work (as long as you only call it on the appropriate thing), you can also alternately just pass the player object in as a parameter. 
For example:
in custom_funcs.py
`py
def inputPlusTwo(self):
    return self.inputx+2`
in models.py for whatever app
'py
class Player(BasePlayer):
    input=models.IntegerField(...)`
in pages.py for whatever app
`py
def vars_for_template(self):
     return dict(self.player.inputPlusTwo())`

**Comment by ianchadd** [comment]
Thanks! Funny - I was just looking at this code for another GH issue. 

I'll also add (for posterity) that custom_classes.py provides another solution for this, though with a reverse order. It defines a new BasePlayer class and endows it with a bunch of methods. 

Then in models.py you use something like

`class Player(DataPlayer):
    pass`

in pages.py
`    def vars_for_template(self):
        self.player.calc_stats(game_name, participants)`

where calc_stats() was defined in the DataPlayer class in custom_classes.py.

**Comment by mcdaij** [comment]
Brief addendum to this since I was messing around with some of this a bit more to add some efficiency to some of the TPG project code, defining a new player class in custom_classes runs into a couple problems because it requires Group and Subsession classes to be defined in the same file can end up conflicting with other places. Also the first suggestion I made actually requires an additional line in order to work as intended where you add the function to the class BasePlayer after it's declaration so custom_funcs would have to read: 
```py
from otree.api import BasePlayer
def inputPlusTwo(self):
    return self.inputx+2
BasePlayer.inputPlusTwo=inputPlusTwo
```
