### ISSUE TITLE
IAT

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#245]
Data appears to not be stored in .csv file but it is in the participant vars?

**Comment by ianchadd** [comment]
Yes - data does not get saved in the IAT csv file. This is because of a weird issue with the data structure used in this code - long story, easier to explain over a call.

Response times and everything get saved in the participant vars and then pushed to the prolific_ID_end csv in a player variable for cleaning later. 

Screenshot below shows the data structure in the participant vars. It is saved as varname "trial X block Y trial ID Z" = (key_entry, millisecond_response_time, correct). We can then separate these out (or not) by block, trial, etc. when data cleaning in stata.

Q for @boonhankoh: is this enough info to do analysis of the IAT data? I've never worked with this data before. 

![Screen Shot 2020-09-02 at 2 49 56 PM](https://user-images.githubusercontent.com/58232760/92024049-a375bb80-ed2b-11ea-9f27-26ca8cd115bd.png)

**Comment by boonhankoh** [comment]
Theoretically I think that's enough for analysis. I need to look at the
actual file that is generated, but basically it's sufficient to get a
measure of whether subjects are making mistakes or not for each question.

Boon Han

**Comment by ianchadd** [comment]
Btw we will also have a record of which categories and stimuli go into which blocks. So if the measure we need is an error rate for each block (gay vs straight, etc.) we can certainly back out that info.

**Comment by boonhankoh** [comment]
Great! ✌🏼

**Comment by boonhankoh** [comment]
@ianchadd we can also chat about this briefly tomorrow. Not clear what you mean here by "blocks", but it's also getting a bit late, so I might leave this to tomorrow.

**Comment by boonhankoh** [comment]
Note to self for discussion:
1. Need to capture response time for **correct** response.
2. Hence, if mistakes are made, that is captured. Importantly, need to capture time at which the correction is made -- this time incorporates penalties due to error.
3. Overall measure is difference in response time between two blocks. 
4. References: Greenwald et al. (J Pers and Social Psych, 1998). More recent algorithm in Greenwald et al. (Attitudes and Social Cognition, 2003)

**Comment by boonhankoh** [comment]
@ianchadd:
Check regarding order variation. Don't worry if it's not possible.
Check IAT - is there a record of incorrect responses only? We need to make sure the 'corrected' response is also captured. This is important.

Read: Greenwald et al. (J Pers and Social Psych, , 2003), Nosek et al. (2007) provides a good summary of this (p.273).

**Comment by boonhankoh** [comment]
![image](https://user-images.githubusercontent.com/61990915/92257642-7f51e000-eecd-11ea-98cb-e9677be23627.png)
