### ISSUE TITLE
Text edits

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#98]
**General Text Edits:** 

1. Introduction/Intro : 
- "... you will receive a participation payment of **$2**" instead of $1.50. 
- "Your entire payment ($**2** ..."  instead of $1.50
-add the following at the end of this page: "Finally, please note that this research does not employ deception. This means that the instructions that you are about to read are true and not deceptive. This is regulated by the researchers’ intuitional ethics committees."

2. /Introduction/Instructions:
- "In this study, you will be asked to complete **four** different games." instead of five. 
-"In addition to your participation payment of **$2**" instead of $1.50
-"we will randomly select one of the **four** games " instead of five
-"once you have completed all **four** games" instead of five

3. Introduction/Counting_Task:
-"As mentioned before, you will participate in **four** games." not five

4. Introduction_Practice/Practice:
- "...click Submit" a period is missing at the end of the sentence. 

5. Game_3/Instructions
-"...You will not be informed of how you did in the tournament until all **four** tasks have been completed." 

6. Similarly, I think the same wording was used also in the instructions for game-4. I missed it, but if that is the case, then we need to fix the same wording on game 4. 

**Just for SEED Data:** 
1. Game_2/Instructions:
-under determining payments, remove the following section:
"Note: nothing you do in this study will affect the payoffs of any other participants in this study. Your group is constructed using answers from participants who already participated in this study. Those subjects have already been paid and are not affected by your choices at all."

2. Game_3/Instructions
-"...You will not be informed of how you did in the tournament until **everyone have completed this study**." 
- remove "Note: nothing you do in this study will affect the payoffs of any other participants in this study. Your group is constructed using answers from participants who already participated in this study. Those subjects have already been paid and are not affected by your choices at all."

3. Game_4/Instructions (I may be wrong about this page info, I forgot to write it down)
-You will not be informed of how you did in the tournament until  **everyone have completed this study.**"

4. Survey/Summary:
Thank you for your participation. We will calculate your earnings after everyone has participated in the experiment and pay your earnings within 21 days.

**Comment by ianchadd** [comment]
- [ ] **General Text Edits:** 
- [ ] 
- [ ] 1. Introduction/Intro : 
- [ ] 
- [ ] - [ ] - "... you will receive a participation payment of **$2**" instead of $1.50. 
- [ ] 
- [ ] 
- [ ] - "Your entire payment ($**2** ..."  instead of $1.50
- [ ] -add the following at the end of this page: "Finally, please note that this research does not employ deception. This means that the instructions that you are about to read are true and not deceptive. This is regulated by the researchers’ intuitional ethics committees."
- [ ] 
- [ ] 2. /Introduction/Instructions:
- [ ] - "In this study, you will be asked to complete **four** different games." instead of five. 
- [ ] -"In addition to your participation payment of **$2**" instead of $1.50
- [ ] -"we will randomly select one of the **four** games " instead of five
- [ ] -"once you have completed all **four** games" instead of five
- [ ] 
- [ ] 3. Introduction/Counting_Task:
- [ ] -"As mentioned before, you will participate in **four** games." not five
- [ ] 
- [ ] 4. Introduction_Practice/Practice:
- [ ] - "...click Submit" a period is missing at the end of the sentence. 
- [ ] 
- [ ] 5. Game_3/Instructions
- [ ] -"...You will not be informed of how you did in the tournament until all **four** tasks have been completed." 
- [ ] 
- [ ] 6. Similarly, I think the same wording was used also in the instructions for game-4. I missed it, but if that is the case, then we need to fix the same wording on game 4. 
- [ ] 
- [ ] 
- [ ] **Just for SEED Data:** 
- [ ] 1. Game_2/Instructions:
- [ ] -under determining payments, remove the following section:
- [ ] "Note: nothing you do in this study will affect the payoffs of any other participants in this study. Your group is constructed using answers from participants who already participated in this study. Those subjects have already been paid and are not affected by your choices at all."
- [ ] 
- [ ] 2. Game_3/Instructions
- [ ] -"...You will not be informed of how you did in the tournament until **everyone have completed this study**." 
- [ ] - remove "Note: nothing you do in this study will affect the payoffs of any other participants in this study. Your group is constructed using answers from participants who already participated in this study. Those subjects have already been paid and are not affected by your choices at all."
- [ ] 
- [ ] 3. Game_4/Instructions (I may be wrong about this page info, I forgot to write it down)
- [ ] -You will not be informed of how you did in the tournament until  **everyone have completed this study.**"
- [ ] 
- [ ] 4. Survey/Summary:
- [ ] Thank you for your participation. We will calculate your earnings after everyone has participated in the experiment and pay your earnings within 21 days. 
- [ ] 
- [ ]

**Comment by ianchadd** [comment]
Note: some of the pages with "Note: ..." on it for Seed data have alternative text that highlights that (for example) decisions in Game 3 affect no other participants (since performance is compared to group performance in Game 2).
